"""Deterministic fast-exponential variant of the pinned fp16 attention source.

The base source is generated by triton-msl at pinned commit
182c1820fd24a836d565e1da842f28414de64084 and remains byte-verifiable.  This
variant changes only the two online-softmax exponential sites in each of the
generator's full and tail blocks.  MMA accumulation and normalization state
remain fp32.  The retained upstream MIT licence is in
``solution/third_party/triton-msl-LICENSE``.
"""

from solution.case14_metal_fp16 import CAUSAL_FLASH_ATTENTION_FP16_HD64


FAST_EXP_REPLACEMENTS = (
    (
        "tg_alpha[r] = exp(m_prev - m_new);",
        "tg_alpha[r] = fast::exp(m_prev - m_new);",
    ),
    (
        "float p = exp(tg_S[pr*BN+cj] - mr);",
        "float p = fast::exp(tg_S[pr*BN+cj] - mr);",
    ),
)


def make_fast_exp_source(source: str) -> str:
    for old, new in FAST_EXP_REPLACEMENTS:
        observed = source.count(old)
        if observed != 2:
            raise RuntimeError(
                f"base source drift for {old!r}: expected 2, got {observed}"
            )
        source = source.replace(old, new)
    return source


CAUSAL_FLASH_ATTENTION_FP16_FAST_EXP_HD64 = make_fast_exp_source(
    CAUSAL_FLASH_ATTENTION_FP16_HD64
)
